/** Site chrome for server-rendered pages (documents, returns): header, footer, math, people and path links are applied by the caller. */
const esc = (s: unknown) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]!));
import { shareMeta } from "./share.js";
import { jsonLd, crumbsFromHtml, demoteHeadings, plainDescription } from "./seo.js";
/** `robots` keeps operational pages (jobs, asks, who holds what) out of search; `ld` is the page's schema.org data, to which the
 *  breadcrumb trail is added. The title leads with the heading when there is one, so "Return #812" reads as what it is in a result. */
export function page(opts: { title: string; crumbs: string; eyebrow?: string; heading?: string; meta?: string; body: string; aside?: string; dataPage?: string; description?: string; path?: string; robots?: string; ld?: object[]; type?: string }): string {
  const heading = opts.heading ? plainDescription(opts.heading, 120) : "";
  const title = heading && !opts.title.startsWith(heading) ? `${heading} · ${opts.title}` : opts.title;
  const trail = crumbsFromHtml(opts.crumbs, { name: heading || opts.title, path: opts.path });
  const ld = [...(opts.ld ?? []), ...(trail ? [trail] : [])];
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} · solveathome</title>${shareMeta({ title: `${heading || opts.title} · solveathome`, description: opts.description, path: opts.path, robots: opts.robots, type: opts.type })}${ld.length ? jsonLd({ "@context": "https://schema.org", "@graph": ld }) : ""}<link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/assets/app.css?v=27"><script defer src="https://umami.infessa.com/script.js" data-website-id="3c56339a-8792-42b6-b506-628db725c596"></script><style>.doc-meta{display:flex;flex-wrap:wrap;gap:.4rem 1.2rem;font-size:.8125rem;color:var(--mut);margin:0 0 1.5rem}.doc-meta .tag{font-family:var(--mono);font-size:.75rem;border:1px solid var(--line);border-radius:3px;padding:0 .4rem;color:var(--fg)}.doc-side{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:2.5rem;margin:2rem 0}.doc-side ul{padding-left:1.1rem;font-size:.875rem;line-height:1.7}.doc-side h3{margin-bottom:.5rem}.doc-side .document h1,.doc-side .document h2,.doc-side .document h3{font-size:1rem;margin:.75rem 0 .35rem;letter-spacing:0}.doc-side .document{font-size:.875rem;line-height:1.7}.doc-side li{margin-bottom:.75rem}@media(max-width:800px){.doc-side{grid-template-columns:1fr}}</style></head><body data-page="${esc(opts.dataPage ?? "document")}"><header data-site-header></header><main class="shell document-main" id="main"><nav class="breadcrumb" aria-label="Breadcrumb">${opts.crumbs}</nav>${opts.heading ? `<div class="page-heading"><div>${opts.eyebrow ? `<p class="eyebrow">${esc(opts.eyebrow)}</p>` : ""}<h1>${esc(opts.heading)}</h1></div></div>` : ""}${opts.meta ?? ""}${opts.aside ?? ""}<article class="document">${opts.heading ? demoteHeadings(opts.body) : opts.body}</article></main><footer data-site-footer></footer><script src="/assets/ui.js?v=18"></script><script src="/assets/who.js?v=4"></script><script src="/assets/math.js?v=1"></script><script>loadWho(document.querySelector("#who"));</script></body></html>`;
}
export { esc };
