// Synthetic HTTP/database contracts only; the real pilot is separately compiled and independently reviewed.
import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import express from 'express';
if(!process.env.TEST_DATABASE_URL) throw new Error('Use a disposable TEST_DATABASE_URL');
process.env.DATABASE_URL=process.env.TEST_DATABASE_URL;
const tmp=mkdtempSync(join(tmpdir(),'sah-exposition-'));process.env.FILES_DIR=join(tmp,'files');process.env.DOCS_DIR=join(tmp,'repos');process.env.OVERLAY_DIR=join(tmp,'overlay');process.env.PROJECTS_DIR=join(tmp,'projects');
const {one,q,pool,migrate}=await import('../src/db/index.ts');
const files=await import('../src/lib/files.ts');
const {TERMS_VERSION}=await import('../src/lib/terms.ts');
const {issueToken,modelTier}=await import('../src/lib/auth.ts');
const {job,composeReviewBrief,resolveReturn}=await import('../src/routes/job.ts');
const {papers,listPapers}=await import('../src/routes/papers.ts');
const {queuePaperExposition,reconcilePaperExpositions,expositionSource}=await import('../src/lib/paper-exposition.ts');
const {leanFixture}=await import('./fixtures/lean.mjs');
const {leanExecutionFixture}=await import('./fixtures/lean-execution.mjs');
const {leanStatementBinding}=await import('../src/lib/lean-verification.ts');
const hash=s=>createHash('sha256').update(s).digest('hex');
let pid,uid,slug,token,server,base,proof,receipt,statementReview,task,tex,map,pdf,compilation,attached,submission;
before(async()=>{
  await migrate();await modelTier('gpt-6.1-sol');await modelTier('claude-opus-5-5');
  slug='exposition-'+randomUUID().slice(0,8);
  uid=Number((await one(`INSERT INTO users(github_id,handle,terms_version,terms_accepted_at) VALUES($1,$2,$3,now()) RETURNING id`,[910000000+Math.floor(Math.random()*1e8),slug,TERMS_VERSION])).id);
  pid=Number((await one(`INSERT INTO problems(slug,name,repo_url,status_md,researcher_user_id,discovery_share) VALUES($1,'Exposition fixture','https://example.org/repo','open',$2,0) RETURNING id`,[slug,uid])).id);
  token=await issueToken(uid,'fixture');await q(`INSERT INTO channels(problem_id,path,title) VALUES($1,'','Fixture')`,[pid]);
  const {plan,artifacts}=leanFixture();
  for(const [path,content] of artifacts) await files.store(uid,'gpt-6.1-sol',path.split('/').at(-1)+'.txt','txt',content);
  const paper=artifacts.find(a=>a[0]==='paper.md');await q(`INSERT INTO papers(problem_id,slug,title,current_file_sha,kind,status) VALUES($1,'example','Fixture',$2,'draft','reviewed')`,[pid,hash(paper[1])]);
  const insert=async p=>one(`INSERT INTO returns(problem_id,type,user_id,model,provider,report_md,transcript,status,effort,verification_plan,verification_fingerprint) VALUES($1,'formalize',$2,'gpt-6.1-sol','openai','Fixture only','t','accepted','high',$3,$4) RETURNING *`,[pid,uid,JSON.stringify(p),hash(JSON.stringify(p))]);
  const configRoot=join(process.env.PROJECTS_DIR,slug);mkdirSync(configRoot,{recursive:true});writeFileSync(join(configRoot,'project.json'),JSON.stringify({slug,name:'Synthetic fixture',lean_main_theorems:[{paper_slug:'example',manuscript_sha256:plan.lean.manuscript_sha256,statement_binding:leanStatementBinding(plan.lean),required_claim_ids:['claim1'],unproved_claims:[]}]}));
  const proposal=await insert(plan);
  statementReview=await one(`INSERT INTO reviews(return_id,user_id,model,provider,verdict,rung,notes_md,trusted,effort,lean_statement_review) VALUES($1,$2,'claude-opus-5-5','anthropic','accept','proven','Synthetic fixture',true,'high',$3) RETURNING id`,[proposal.id,uid,JSON.stringify({binding_sha256:leanStatementBinding(plan.lean),meaning_md:'Synthetic mapping'})]);
  plan.lean.statement_review_id=Number(statementReview.id);proof=await insert(plan);
  const f=await leanExecutionFixture(proof,uid);receipt=await f.submit();
  await q(`INSERT INTO reviews(return_id,user_id,model,provider,verdict,rung,notes_md,trusted,effort,verification_receipt_id,verification_sufficiency_md) VALUES($1,$2,'claude-opus-5-5','anthropic','accept','proven','Synthetic fixture',true,'high',$3,$4)`,[proof.id,uid,receipt.id,'Synthetic test review assesses the exact mapped claims, evidence coverage and all assumptions. No real model or Lean execution is asserted.']);
  const app=express();app.use(express.json({limit:'6mb'}));app.use('/projects/:slug',job);app.use('/projects/:slug',papers);app.use((e,req,res,next)=>res.status(e.status??500).json({error:e.message}));
  server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}/projects/${slug}`;
});
after(async()=>{
  if(server) await new Promise(r=>server.close(r));
  if(!pid) { await pool.end();rmSync(tmp,{recursive:true,force:true});return; }
  await q(`DELETE FROM file_refs WHERE file_sha IN (SELECT sha256 FROM files WHERE user_id=$1)`,[uid]);
  await q(`DELETE FROM messages WHERE user_id=$1`,[uid]);await q(`DELETE FROM credits WHERE problem_id=$1`,[pid]);
  await q(`DELETE FROM verification_runs WHERE subject_return_id IN (SELECT id FROM returns WHERE problem_id=$1)`,[pid]);
  await q(`DELETE FROM return_decisions WHERE return_id IN (SELECT id FROM returns WHERE problem_id=$1)`,[pid]);
  await q(`DELETE FROM reviews WHERE return_id IN (SELECT id FROM returns WHERE problem_id=$1)`,[pid]);
  await q(`DELETE FROM assignment_attempts WHERE problem_id=$1`,[pid]);await q(`UPDATE returns SET job_id=NULL WHERE problem_id=$1`,[pid]);
  await q(`DELETE FROM jobs WHERE problem_id=$1`,[pid]);await q(`DELETE FROM returns WHERE problem_id=$1`,[pid]);
  await q(`DELETE FROM papers WHERE problem_id=$1`,[pid]);await q(`DELETE FROM sessions WHERE problem_id=$1`,[pid]);
  await q(`DELETE FROM pool WHERE problem_id=$1`,[pid]);await q(`DELETE FROM channel_members WHERE user_id=$1`,[uid]);await q(`DELETE FROM channels WHERE problem_id=$1`,[pid]);
  await q(`DELETE FROM files WHERE user_id=$1`,[uid]);await q(`DELETE FROM tokens WHERE user_id=$1`,[uid]);await q(`DELETE FROM reputation WHERE user_id=$1`,[uid]);
  await q(`DELETE FROM problems WHERE id=$1`,[pid]);await q(`DELETE FROM users WHERE id=$1`,[uid]);
  const residue=await one(`SELECT count(*) AS n FROM problems WHERE id=$1`,[pid]);assert.equal(Number(residue.n),0);
  await pool.end();rmSync(tmp,{recursive:true,force:true});
});
const call=async(body,model='gpt-6.1-sol')=>fetch(base+'/result',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','x-model':model,'x-effort':'high'},body:JSON.stringify({transcript:'Synthetic fixture; no mathematical result.',transcript_approved:true,...body})});
const store=async(name,ext,body)=>(await files.store(uid,'gpt-6.1-sol',name,ext,body)).sha;
test('current acceptance queues one ordinary paper task; pending and revoked sources do not qualify or regenerate',async()=>{
  assert.equal((await expositionSource(Number(proof.id),pid)).current,true);
  task=await queuePaperExposition(Number(proof.id),pid);assert.ok(task);
  assert.equal(await queuePaperExposition(Number(proof.id),pid),task);
  await reconcilePaperExpositions(pid);assert.equal(Number((await one(`SELECT count(*) AS n FROM jobs WHERE problem_id=$1 AND exposition_key IS NOT NULL`,[pid])).n),1);
  await q(`UPDATE returns SET status='pending' WHERE id=$1`,[proof.id]);await reconcilePaperExpositions(pid);
  assert.equal((await one(`SELECT status FROM jobs WHERE id=$1`,[task])).status,'expired');
  await q(`UPDATE returns SET status='accepted' WHERE id=$1`,[proof.id]);assert.equal(await queuePaperExposition(Number(proof.id),pid),task);assert.equal((await one(`SELECT status FROM jobs WHERE id=$1`,[task])).status,'expired');
  await q(`UPDATE reviews SET needs_reassessment=true WHERE id=$1`,[statementReview.id]);assert.equal(await queuePaperExposition(Number(proof.id),pid),null);
  await q(`UPDATE reviews SET needs_reassessment=false WHERE id=$1`,[statementReview.id]);
});
test('HTTP submission rejects changed claims without orphan rows, then records a separate version and one fidelity review',async()=>{
  tex=await store('exposition.tex','tex','\\documentclass{article}\n\\begin{document}Fixture\\end{document}\n');
  const bytes=Buffer.from('%PDF-1.4\nSynthetic transport fixture only\n%%EOF\n');
  pdf=await store('pdf.json','json',JSON.stringify({schema:'paper-exposition-pdf-v1',bytes:bytes.length,sha256:hash(bytes),base64:bytes.toString('base64')}));
  const log=await store('compile.log','log','Synthetic test log; no TeX execution.');
  compilation=await store('compilation.json','json',JSON.stringify({schema:'paper-exposition-compile-v1',status:'pass',exit_code:0,tex_sha256:tex,pdf_sha256:hash(bytes),toolchain:{name:'fixture',version:'synthetic'},command:'Synthetic fixture -no-shell-escape',isolation:{network:'none',shell_escape:false,host_files:'none',unprivileged:true,inputs_readonly:true},log_sha256:log}));
  const m={schema:'paper-exposition-map-v1',source_return_id:Number(proof.id),source_fingerprint:proof.verification_fingerprint,receipt_id:Number(receipt.id),tex_sha256:tex,claims:[{source_claim_id:'claim1',...proof.verification_plan.lean.claims[0],tex_locator:'Theorem 1'}],unproved_claims:[]};
  const bad=structuredClone(m);bad.claims[0].declaration='Example.stronger';const badMap=await store('bad-map.json','json',JSON.stringify(bad));
  map=await store('map.json','json',JSON.stringify(m));attached=[tex,pdf,compilation,log,map];
  const body={type:'paper',report_md:'Synthetic exposition fidelity fixture.',author_rung:'proven',files:attached,paper:{slug:'example',file:tex,exposition:{source_return_id:Number(proof.id),source_fingerprint:proof.verification_fingerprint,receipt_id:Number(receipt.id),claim_map_sha256:map,pdf_sha256:pdf,compilation_sha256:compilation}}};
  const refused=await call({...body,files:[...attached,badMap],paper:{...body.paper,exposition:{...body.paper.exposition,claim_map_sha256:badMap}}});assert.equal(refused.status,400,await refused.text());
  assert.equal(Number((await one(`SELECT count(*) AS n FROM returns WHERE problem_id=$1 AND type='paper'`,[pid])).n),0);
  const good=await call(body),result=await good.json();assert.equal(good.status,200,JSON.stringify(result));submission=result.return_id;
  const r=await one(`SELECT * FROM returns WHERE id=$1`,[submission]);assert.equal(r.revision_sha,null);assert.equal(r.revision_path,null);assert.equal(r.paper_exposition.tex_sha256,tex);
  assert.notEqual((await one(`SELECT current_file_sha FROM papers WHERE problem_id=$1`,[pid])).current_file_sha,tex);
  assert.equal(Number((await one(`SELECT count(*) AS n FROM jobs WHERE parent_return_id=$1 AND type='review'`,[submission])).n),1);
  const brief=(await composeReviewBrief(submission,pid)).brief;assert.match(brief,/FINISHED LaTeX/);assert.match(brief,/do not execute Lean again/);
});
test('ordinary accepting review must bind this version; downloads preserve bytes and stale evidence stays visible',async()=>{
  const e=(await one(`SELECT paper_exposition FROM returns WHERE id=$1`,[submission])).paper_exposition;
  const unbound=await one(`INSERT INTO reviews(return_id,user_id,model,provider,verdict,rung,notes_md,trusted,effort) VALUES($1,$2,'claude-opus-5-5','anthropic','accept','proven','Synthetic legacy or series vote without an exposition mapping',true,'high') RETURNING id`,[submission,uid]);
  assert.match(await resolveReturn(submission),/^pending/);
  assert.equal((await one(`SELECT status FROM returns WHERE id=$1`,[submission])).status,'pending');
  await q(`DELETE FROM reviews WHERE id=$1`,[unbound.id]);
  const body={type:'review',return_id:submission,verdict:'accept',rung:'proven',notes_md:'Synthetic ordinary fidelity review.'};
  const bad=await call(body,'claude-opus-5-5');assert.equal(bad.status,400,await bad.text());
  const binding={tex_sha256:tex,claim_map_sha256:map,pdf_sha256:pdf,source_fingerprint:e.source_fingerprint,reviewed_claim_ids:['claim1'],fidelity_md:'Synthetic correspondence review checks the exact source statement, unchanged formal parameters and every scoped artifact. This is a database test, not mathematical evidence.'};
  const good=await call({...body,paper_exposition_review:binding},'claude-opus-5-5');const result=await good.json();assert.equal(good.status,200,JSON.stringify(result));
  assert.equal((await one(`SELECT status FROM returns WHERE id=$1`,[submission])).status,'accepted');
  let view=await (await fetch(base+'/papers/example',{headers:{accept:'application/json'}})).json();assert.equal(view.expositions[0].evidence.current,true);
  const current=async()=>({list:(await listPapers(pid,slug))[0],page:await(await fetch(base+'/papers/example',{headers:{accept:'application/json'}})).json()});
  const eligible=await current();for(const paper of [eligible.list,eligible.page.paper])assert.equal(paper.reviewed_pdf.return_id,submission);
  const currentPdf=base+`/papers/example/expositions/${submission}/pdf?current=1`;
  assert.equal(eligible.page.paper.reviewed_pdf.url.endsWith('/pdf?current=1'),true);
  assert.equal((await fetch(currentPdf)).status,200);
  const html=await fetch(base+'/papers/example',{headers:{accept:'text/html'}});assert.equal(html.headers.get('cache-control'),'no-store');assert.match(await html.text(),new RegExp(`href="/projects/${slug}/papers/example/expositions/${submission}/pdf\\?current=1">View PDF`));
  // A higher-id pending revision never inherits the old edition's fidelity vote.
  const newer=await one(`INSERT INTO returns(problem_id,type,user_id,model,provider,report_md,transcript,status,effort,paper_slug,paper_exposition) VALUES($1,'paper',$2,'gpt-6.1-sol','openai','Synthetic newer edition','t','pending','high','example',$3) RETURNING id`,[pid,uid,JSON.stringify(e)]);
  for(const file of attached)await q(`INSERT INTO file_refs(file_sha,ref_type,ref_id) VALUES($1,'return',$2)`,[file,newer.id]);
  assert.equal((await current()).list.reviewed_pdf.return_id,submission);
  await q(`UPDATE returns SET status='rejected' WHERE id=$1`,[newer.id]);assert.equal((await current()).page.paper.reviewed_pdf.return_id,submission);
  await q(`UPDATE reviews SET needs_reassessment=true WHERE return_id=$1`,[submission]);for(const paper of [(await current()).list,(await current()).page.paper])assert.equal(paper.reviewed_pdf,null);
  const reassessed=await fetch(currentPdf);assert.equal(reassessed.status,409);assert.equal(reassessed.headers.get('cache-control'),'no-store');
  assert.equal((await fetch(base+`/papers/example/expositions/${submission}/pdf`)).status,200,'Historical version is still accessible');
  await q(`UPDATE reviews SET needs_reassessment=false WHERE return_id=$1`,[submission]);

  const download=await fetch(base+`/papers/example/expositions/${submission}/pdf`);assert.equal(download.status,200);assert.equal(download.headers.get('content-type'),'application/pdf');assert.match(download.headers.get('content-disposition'),/^inline; filename="exposition-[0-9]+-pdf\.pdf"$/);assert.equal(download.headers.get('x-content-type-options'),'nosniff');assert.equal(hash(Buffer.from(await download.arrayBuffer())),JSON.parse(files.read(pdf)).sha256);
  const sourceDownload=await fetch(base+`/papers/example/expositions/${submission}/source`);assert.equal(sourceDownload.status,200);assert.match(sourceDownload.headers.get('content-disposition'),/^attachment/);assert.equal(sourceDownload.headers.get('x-content-type-options'),'nosniff');
  await q(`UPDATE returns SET status='pending' WHERE id=$1`,[proof.id]);view=await (await fetch(base+'/papers/example',{headers:{accept:'application/json'}})).json();assert.equal(view.expositions[0].evidence.current,false);assert.equal(view.paper.reviewed_pdf,null);assert.equal((await current()).list.reviewed_pdf,null);
  assert.equal((await fetch(currentPdf)).status,409,'A stale page cannot open its PDF as a currently eligible selection');
  const staleHtml=await(await fetch(base+'/papers/example',{headers:{accept:'text/html'}})).text();assert.doesNotMatch(staleHtml,/>View PDF<\/a>/);
  assert.equal((await fetch(base+`/papers/example/expositions/${submission}/pdf`)).status,200,'Stale evidence preserves historical bytes');
  await q(`UPDATE returns SET status='accepted' WHERE id=$1`,[proof.id]);
  await files.remove(pdf,uid,'Synthetic artifact removal');assert.equal((await fetch(base+`/papers/example/expositions/${submission}/pdf`)).status,410);for(const paper of [(await current()).list,(await current()).page.paper])assert.equal(paper.reviewed_pdf,null);
});
