import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createLab} from './simulation/harness.mjs';
import {parseResearchTask} from '../src/lib/shared-research-format.ts';
import {workScopeHash} from '../src/lib/work-disposition-format.ts';
const root=mkdtempSync(join(tmpdir(),'work-disposition-config-'));process.env.PROJECTS_DIR=root;
let lab;before(async()=>{lab=await createLab();});after(async()=>{await lab?.close();rmSync(root,{recursive:true,force:true});});
function config(w,template='md5',challenge=false){const slug=w.base.split('/').at(-1),c=JSON.parse(readFileSync(new URL(`../projects/${template}/project.json`,import.meta.url)));if(!challenge)delete c.challenge;Object.assign(c,{slug,listed:true});mkdirSync(join(root,slug));writeFileSync(join(root,slug,'project.json'),JSON.stringify(c));return slug;}
const task=(source,topic='self-match.study-2')=>parseResearchTask({intent:'extend',topic_ids:[topic],predecessor_returns:[source],unresolved_obligation_md:'The exact step-61 rejection gate under this fixed corpus.',changed_premise_md:'Unchanged gate and corpus.',expected_evidence_md:'Exact dependence comparison.',stop_if_md:'Prior evidence answers this exact corpus.',domain_md:'Full 64-step MD5, RFC IV, ASCII32, fixed corpus; no nonlinear-filter impossibility.'});
const stop=source=>({predecessor_returns:[source],review_ids:[],message_ids:[],comparison_md:'The predecessor already performed exactly this comparison; no new scientific work.',remaining_gap_md:'Different corpora remain open.',reopen_when_md:'Changed corpus or independent replication objective.'});
async function job(w,t,extra={}){return w.one(`INSERT INTO jobs(problem_id,type,title,brief_md,min_tier,budget_hours,priority,research_task,work_scope_sha256,origin_key) VALUES($1,'explore',$2,$2,99,0.1,10,$3,$4,$5) RETURNING *`,[w.pid,t.unresolved_obligation_md,JSON.stringify(t),workScopeHash(t),extra.origin??null]);}
const decision=(check,extra={})=>({decision:'covered',scope_sha256:check.scope_sha256,input_sha256:check.input_sha256,rationale_md:'The cited source and its corrections cover only this unchanged experiment.',reopen_when_md:'Changed premises, source corrections or deliberate replication.',...extra});
test('compact stop, deduplicated trusted comparison, exact suppression and correction reopening through HTTP',async()=>{
 const w=await lab.project('operational-md5',81),slug=config(w);const a=await w.actor('author','gpt-6-astra'),judge=await w.actor('judge','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),t=task(prior.return_id),first=await job(w,t),second=await job(w,t);
 await w.take(a,j=>Number(j.job_id)===Number(first.id));
 const k=await a.submit({known_work:stop(prior.return_id)});assert.equal(k.status,'recorded');assert.equal(k.reviews_requested,0);assert.ok(k.work_check_job_id);
 assert.equal((await w.one(`SELECT count(*)::int AS n FROM jobs WHERE parent_return_id=$1 AND type='review'`,[k.return_id])).n,0);
 await w.take(a,j=>Number(j.job_id)===Number(second.id));const k2=await a.submit({known_work:stop(prior.return_id)});assert.equal(k2.work_check_job_id,k.work_check_job_id);
 const assigned=await w.take(judge,j=>Boolean(j.work_check));assert.equal(assigned.type,'explore');assert.match(assigned.brief_md,/not scientific acceptance/);
 const retry=await judge.request('/start');assert.deepEqual(retry.work_check,assigned.work_check);
 const verdict=await judge.submit({work_disposition:decision(assigned.work_check)});assert.equal(verdict.status,'recorded');
 assert.equal((await w.read(`/return/${prior.return_id}`)).status,'pending');
 const {retireCoveredWork,currentWorkDisposition,queueWorkCheck}=await import('../src/lib/work-disposition.ts');
 await w.q("UPDATE returns SET created_at=created_at-interval '7 days' WHERE id=$1",[verdict.return_id]);
 assert.ok(await currentWorkDisposition(w.pid,workScopeHash(t)),'age alone cannot reopen unchanged covered work');
 const duplicate=await job(w,t);await retireCoveredWork(w.pid,slug);assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[duplicate.id])).status,'expired');
 const replica=await job(w,{...t,intent:'replication'}),changed=await job(w,{...t,changed_premise_md:'Different candidate corpus.'});await retireCoveredWork(w.pid,slug);
 for(const j of [replica,changed])assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[j.id])).status,'queued');
 assert.equal(await queueWorkCheck(w.pid,slug,null,t,stop(prior.return_id),{}),null);
 await judge.submit({type:'review',return_id:prior.return_id,verdict:'reject',reject_reason:'overclaimed',notes_md:'This old statement also excludes nonlinear filters, which the corpus cannot establish.'});
 assert.equal(await currentWorkDisposition(w.pid,workScopeHash(t)),null);
 const reopened=await job(w,t);await retireCoveredWork(w.pid,slug);assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[reopened.id])).status,'queued');
 assert.ok((await w.read('/work-state')).decisions.every(d=>!d.current));await w.invariant();
});
test('chat nominates scoped evidence without authority; stale or untrusted dispositions cannot suppress work',async()=>{
 const w=await lab.project('chat-investment',52);config(w);const a=await w.actor('a','gpt-6-astra'),j=await w.actor('j','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),contractSource=await a.submit({type:'direction'}),t={...task(prior.return_id),predecessor_returns:[contractSource.return_id]};
 const message=await a.request('/chat/messages',{method:'POST',body:{kind:'challenge',body_md:'This precise obligation appears covered; please compare the predecessor and its corrections.',work_check:{...stop(prior.return_id),task:t}}});
 assert.ok(message.work_check_job_id);assert.deepEqual((await w.read('/work-state')).decisions,[]);
 await a.request(`/start?job=${message.work_check_job_id}`,{status:409,assignment:null,launch:a.launch});
 const assigned=await w.take(j,x=>Boolean(x.work_check));assert.ok(assigned.work_check.sources.message_ids.includes(message.id));assert.deepEqual(assigned.work_check.sources.predecessor_returns,[prior.return_id,contractSource.return_id].sort((a,b)=>a-b));
 await w.q('UPDATE returns SET report_md=report_md || $2 WHERE id=$1',[contractSource.return_id,' A new caveat changes the source.']);
 const result=await j.submit({work_disposition:decision(assigned.work_check)});assert.match(result.warnings.join('\n'),/stale/);
 const state=await w.read('/work-state');assert.equal(state.decisions[0].current,false);
 const bogus=await a.submit({type:'direction',work_disposition:decision(assigned.work_check)});assert.match(bogus.warnings.join('\n'),/no dispatch authority/);
 const other=await lab.project('other-source',52),oa=await other.actor('oa','gpt-6-astra'),or=await oa.submit({type:'direction'});
 const cross=await a.request('/chat/messages',{method:'POST',body:{body_md:'Compare this pointer.',work_check:{...stop(or.return_id),task:t}}});assert.equal(cross.work_check_job_id,null);
 await w.invariant();
});
test('reviewer readiness and reviews-only dispatch include bounded judgments, then ordinary reviews between comparisons',async()=>{
 const w=await lab.project('reviewer-setup',61),slug=config(w);const a=await w.actor('a','gpt-6-astra'),j=await w.actor('j','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),t=task(prior.return_id);const {queueWorkCheck}=await import('../src/lib/work-disposition.ts');
 await queueWorkCheck(w.pid,slug,null,t,stop(prior.return_id),{author_model:a.model});
 const ready=await j.request('/ready?work=reviews');assert.equal(ready.work_comparisons,1);
 const first=await j.request('/start?share=25&work=reviews',{assignment:null,launch:j.launch});j.session=first.session;j.held=first;
 assert.ok(first.work_check);assert.equal(first.assignment_reason.policy,'trusted assignment comparison');assert.doesNotMatch(first.brief_md,/Search the global body of work first/);
 await j.submit({work_disposition:decision(first.work_check)});
 await queueWorkCheck(w.pid,slug,null,{...t,unresolved_obligation_md:'A different exact comparison.'},stop(prior.return_id),{author_model:a.model});
 assert.equal((await j.request('/ready?work=reviews')).work_comparisons,undefined);
 const second=await j.start();assert.equal(second.type,'review');await w.finish(j);
 assert.equal((await j.request('/ready?work=reviews')).work_comparisons,1);
 const third=await j.start();assert.ok(third.work_check);
 const scientific=await j.submit({request_review:true,work_disposition:decision(third.work_check),research_evidence:{topic_ids:t.topic_ids,scopes:[{key:'new-claim',statement_md:'A separately proposed finite observation.',domain_md:'Fixture only.',kind:'finite',artifact_sha256:[]}]}});
 assert.equal(scientific.status,'pending');assert.match(scientific.warnings.join('\n'),/ordinary intake/);assert.equal((await w.read(`/return/${scientific.return_id}`)).work_disposition,null);await w.invariant();
});
test('a broad MD5 run cannot close the track and a concrete next test is dispatched once',async()=>{
 const w=await lab.project('generic-to-specific',17),slug=config(w,'md5',true);const a=await w.actor('a','gpt-6-astra'),j=await w.actor('j','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),t=task(prior.return_id);
 const run=await job(w,t,{origin:'challenge:md5-mirror-ascii32-v1:fixture'});await w.take(a,x=>Number(x.job_id)===Number(run.id));
 const stopped=await a.submit({known_work:stop(prior.return_id)});const assigned=await w.take(j,x=>Boolean(x.work_check));assert.equal(assigned.work_check.allow_covered,false);
 const wrong=await j.submit({work_disposition:decision(assigned.work_check)});assert.match(wrong.warnings.join('\n'),/no dispatch authority/);
 const {queueWorkCheck,queueWorkNextTasks}=await import('../src/lib/work-disposition.ts');await queueWorkCheck(w.pid,slug,null,t,stop(prior.return_id),{allow_covered:false,author_model:a.model});
 const j2=await w.actor('j2','claude-fable-5-1',{trusted:true});const fresh=await w.take(j2,x=>Boolean(x.work_check));const next={...t,intent:'extend',unresolved_obligation_md:'Compare lazy three-word and all-word observers on identical streams.',changed_premise_md:'Hold kernel and seeds fixed; change observer only.'};
 await j2.submit({work_disposition:decision(fresh.work_check,{decision:'open',next_task:next})});
 await queueWorkNextTasks(w.pid,slug);await queueWorkNextTasks(w.pid,slug);const selected=await w.q("SELECT * FROM jobs WHERE problem_id=$1 AND origin_key LIKE 'work-next:%'",[w.pid]);assert.equal(selected.length,1);assert.equal(selected[0].research_task.unresolved_obligation_md,next.unresolved_obligation_md);assert.deepEqual(selected[0].research_task.predecessor_returns,[prior.return_id]);
 await w.invariant();
});
test('Twin Primes exact O2 investment decisions preserve O1/O3–O7 and the accepted main proof',async()=>{
 const w=await lab.project('operational-twin',22),slug=config(w,'twin-primes');const a=await w.actor('a','gpt-6-astra'),j=await w.actor('j','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),t=task(prior.return_id,'kk-lower-bound.o2');
 // Existing accepted main proof is a fixture; these investment helpers never change it.
 await w.q("UPDATE returns SET status='accepted',final_rung='proven',provisional=false WHERE id=$1",[prior.return_id]);
 await (await import('../src/db/index.ts')).migrate();
 const {queueWorkCheck,retireCoveredWork}=await import('../src/lib/work-disposition.ts');await queueWorkCheck(w.pid,slug,null,t,stop(prior.return_id),{author_model:a.model});
 const assigned=await w.take(j,x=>Boolean(x.work_check));await j.submit({work_disposition:decision(assigned.work_check)});
 const covered=await job(w,t),others=[];for(const topic of ['main','o1','o3','o4','o5','o6','o7'])others.push(await job(w,{...t,topic_ids:[`kk-lower-bound.${topic}`]}));await retireCoveredWork(w.pid,slug);
 assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[covered.id])).status,'expired');for(const x of others)assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[x.id])).status,'queued');
 const main=await w.read(`/return/${prior.return_id}`);assert.equal(main.status,'accepted');assert.equal(main.final_rung,'proven');
});
