import assert from 'node:assert/strict';
import {before,after,test} from 'node:test';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createLab} from './simulation/harness.mjs';
import {parseResearchTask,scopeHash,reportHash} from '../src/lib/shared-research-format.ts';
import {workScopeHash} from '../src/lib/work-disposition-format.ts';
const root=mkdtempSync(join(tmpdir(),'work-disposition-config-'));process.env.PROJECTS_DIR=root;
let lab;before(async()=>{lab=await createLab();});after(async()=>{await lab?.close();rmSync(root,{recursive:true,force:true});});
function config(w,template='md5',challenge=false){const slug=w.base.split('/').at(-1),c=JSON.parse(readFileSync(new URL(`../projects/${template}/project.json`,import.meta.url)));if(!challenge)delete c.challenge;Object.assign(c,{slug,listed:true});mkdirSync(join(root,slug));writeFileSync(join(root,slug,'project.json'),JSON.stringify(c));return slug;}
const task=(source,topic='self-match.study-2')=>parseResearchTask({intent:'extend',topic_ids:[topic],predecessor_returns:[source],unresolved_obligation_md:'The exact step-61 rejection gate under this fixed corpus.',changed_premise_md:'Unchanged gate and corpus.',expected_evidence_md:'Exact dependence comparison.',stop_if_md:'Prior evidence answers this exact corpus.',domain_md:'Full 64-step MD5, RFC IV, ASCII32, fixed corpus; no nonlinear-filter impossibility.'});
const stop=source=>({predecessor_returns:[source],review_ids:[],message_ids:[],comparison_md:'The predecessor already performed exactly this comparison; no new scientific work.',remaining_gap_md:'Different corpora remain open.',reopen_when_md:'Changed corpus or independent replication objective.'});
async function job(w,t,extra={}){return w.one(`INSERT INTO jobs(problem_id,type,title,brief_md,min_tier,budget_hours,priority,research_task,work_scope_sha256,origin_key) VALUES($1,'explore',$2,$2,99,0.1,10,$3,$4,$5) RETURNING *`,[w.pid,t.unresolved_obligation_md,JSON.stringify(t),workScopeHash(t),extra.origin??null]);}
const decision=(check,extra={})=>({decision:'covered',scope_sha256:check.scope_sha256,input_sha256:check.input_sha256,rationale_md:'The cited source and its corrections cover only this unchanged experiment.',reopen_when_md:'Changed premises, source corrections or deliberate replication.',...extra});
test('compact stop, deduplicated trusted comparison, exact suppression and only explicit fresh trusted reopening through HTTP',async()=>{
 const w=await lab.project('operational-md5',81),slug=config(w);const a=await w.actor('author','gpt-6-astra'),judge=await w.actor('judge','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),t=task(prior.return_id),first=await job(w,t),second=await job(w,t);
 await w.take(a,j=>Number(j.job_id)===Number(first.id));
 const k=await a.submit({known_work:stop(prior.return_id)});assert.equal(k.status,'recorded');assert.equal(k.reviews_requested,0);assert.ok(k.work_check_job_id);
 assert.equal((await w.one(`SELECT count(*)::int AS n FROM jobs WHERE parent_return_id=$1 AND type='review'`,[k.return_id])).n,0);
 await w.take(a,j=>Number(j.job_id)===Number(second.id));const k2=await a.submit({known_work:stop(prior.return_id)});assert.equal(k2.work_check_job_id,k.work_check_job_id);
 const assigned=await w.take(judge,j=>Boolean(j.work_check));assert.equal(assigned.type,'explore');assert.match(assigned.brief_md,/not scientific acceptance/);
 const retry=await judge.request('/start');assert.deepEqual(retry.work_check,assigned.work_check);
 const verdict=await judge.submit({work_disposition:decision(assigned.work_check)});assert.equal(verdict.status,'recorded');
 assert.equal((await w.read(`/return/${prior.return_id}`)).status,'pending');
 const {retireCoveredWork,currentWorkDisposition,queueWorkCheck}=await import('../src/lib/work-disposition.ts');
 await w.q("UPDATE returns SET created_at=created_at-interval '7 days' WHERE id=$1",[verdict.return_id]);
 assert.ok(await currentWorkDisposition(w.pid,workScopeHash(t)),'age alone cannot reopen unchanged covered work');
 await a.request('/chat/messages',{method:'POST',body:{body_md:'An arbitrary comment without a scoped nomination.'}});
 assert.equal((await currentWorkDisposition(w.pid,workScopeHash(t))).evidence_current,true);
 assert.equal((await w.one("SELECT count(*)::int AS n FROM jobs WHERE problem_id=$1 AND work_check IS NOT NULL AND status='queued'",[w.pid])).n,0);
 await a.request(`/return/${verdict.return_id}/request-review`,{method:'POST',body:{note:'Inspect the operational record; this does not reopen its assignment.'}});
 assert.equal((await currentWorkDisposition(w.pid,workScopeHash(t))).work_disposition.decision,'covered');
 const unrelatedExpiry=await job(w,t);await w.q("UPDATE jobs SET status='expired',last_release_note='A different expiry reason.' WHERE id=$1",[unrelatedExpiry.id]);
 const duplicate=await job(w,t);await retireCoveredWork(w.pid,slug);assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[duplicate.id])).status,'expired');
 const replica=await job(w,{...t,intent:'replication'}),changed=await job(w,{...t,changed_premise_md:'Different candidate corpus.'});await retireCoveredWork(w.pid,slug);
 for(const j of [replica,changed])assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[j.id])).status,'queued');
 assert.equal(await queueWorkCheck(w.pid,slug,null,t,stop(prior.return_id),{}),null);
 await judge.submit({type:'review',return_id:prior.return_id,verdict:'reject',reject_reason:'overclaimed',notes_md:'This old statement also excludes nonlinear filters, which the corpus cannot establish.'});
 let active=await currentWorkDisposition(w.pid,workScopeHash(t));assert.equal(active.work_disposition.decision,'covered');assert.equal(active.evidence_current,false);
 const suppressed=await job(w,t);await retireCoveredWork(w.pid,slug);assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[suppressed.id])).status,'expired');
 const state=await w.read('/work-state');assert.ok(state.decisions.some(d=>d.suppressed&&d.needs_reconsideration&&!d.evidence_current));
 const checks=await w.q("SELECT * FROM jobs WHERE problem_id=$1 AND work_check IS NOT NULL AND status='queued'",[w.pid]);assert.equal(checks.length,1);assert.equal(checks[0].work_check.base_decision_return_id,verdict.return_id);
 const unauthorized=await a.submit({type:'direction',work_disposition:decision(checks[0].work_check,{decision:'open'})});assert.match(unauthorized.warnings.join('\n'),/no dispatch authority/);
 const judge2=await w.actor('reconsider','claude-fable-5-1',{trusted:true}),held=await w.take(judge2,j=>Boolean(j.work_check));
 await w.q('UPDATE returns SET report_md=report_md || $2 WHERE id=$1',[prior.return_id,' Another correction arrives during the held comparison.']);
 const stale=await judge2.submit({work_disposition:decision(held.work_check,{decision:'open'})});assert.match(stale.warnings.join('\n'),/ineffective/);
 assert.equal((await currentWorkDisposition(w.pid,workScopeHash(t))).work_disposition.decision,'covered');
 const judge3=await w.actor('obsolete-base','claude-fable-5-1',{trusted:true}),obsolete=await w.take(judge3,j=>Boolean(j.work_check));
 await w.fault('An obsolete comparison carries a superseded decision base.',"UPDATE jobs SET work_check=jsonb_set(work_check,'{base_decision_return_id}','null'::jsonb) WHERE id=$1",[obsolete.job_id]);
 const superseded=await judge3.submit({work_disposition:decision(obsolete.work_check,{decision:'open'})});assert.match(superseded.warnings.join('\n'),/superseded/);
 assert.equal((await currentWorkDisposition(w.pid,workScopeHash(t))).work_disposition.decision,'covered');
 const judge4=await w.actor('explicit-reopen','claude-fable-5-1',{trusted:true}),fresh=await w.take(judge4,j=>Boolean(j.work_check));
 const opened=await judge4.submit({work_disposition:decision(fresh.work_check,{decision:'open'})});assert.equal(opened.status,'recorded');
 active=await currentWorkDisposition(w.pid,workScopeHash(t));assert.equal(active.work_disposition.decision,'open');assert.equal(active.evidence_current,true);
 assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[suppressed.id])).status,'queued');assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[unrelatedExpiry.id])).status,'expired');assert.equal((await w.read('/return/'+prior.return_id)).status,'pending');
 await w.invariant();
});
test('chat nominates scoped evidence without authority; stale or untrusted dispositions cannot suppress work',async()=>{
 const w=await lab.project('chat-investment',52);config(w);const a=await w.actor('a','gpt-6-astra'),j=await w.actor('j','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),contractSource=await a.submit({type:'direction'}),t={...task(prior.return_id),predecessor_returns:[contractSource.return_id]};
 const message=await a.request('/chat/messages',{method:'POST',body:{kind:'challenge',body_md:'This precise obligation appears covered; please compare the predecessor and its corrections.',work_check:{...stop(prior.return_id),task:t}}});
 assert.ok(message.work_check_job_id);assert.deepEqual((await w.read('/work-state')).decisions,[]);
 await a.request(`/start?job=${message.work_check_job_id}`,{status:409,assignment:null,launch:a.launch});
 const assigned=await w.take(j,x=>Boolean(x.work_check));assert.ok(assigned.work_check.sources.message_ids.includes(message.id));assert.deepEqual(assigned.work_check.sources.predecessor_returns,[prior.return_id,contractSource.return_id].sort((a,b)=>a-b));
 await w.q('UPDATE returns SET report_md=report_md || $2 WHERE id=$1',[contractSource.return_id,' A new caveat changes the source.']);
 const result=await j.submit({work_disposition:decision(assigned.work_check)});assert.match(result.warnings.join('\n'),/stale/);
 const state=await w.read('/work-state');assert.equal(state.decisions[0].current,false);
 const bogus=await a.submit({type:'direction',work_disposition:decision(assigned.work_check)});assert.match(bogus.warnings.join('\n'),/no dispatch authority/);
 const other=await lab.project('other-source',52),oa=await other.actor('oa','gpt-6-astra'),or=await oa.submit({type:'direction'});
 const cross=await a.request('/chat/messages',{method:'POST',body:{body_md:'Compare this pointer.',work_check:{...stop(or.return_id),task:t}}});assert.equal(cross.work_check_job_id,null);
 await w.invariant();
});
test('reviewer readiness and reviews-only dispatch include bounded judgments, then ordinary reviews between comparisons',async()=>{
 const w=await lab.project('reviewer-setup',61),slug=config(w);const a=await w.actor('a','gpt-6-astra'),j=await w.actor('j','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),t=task(prior.return_id);const {queueWorkCheck}=await import('../src/lib/work-disposition.ts');
 await queueWorkCheck(w.pid,slug,null,t,stop(prior.return_id),{author_model:a.model});
 const ready=await j.request('/ready?work=reviews');assert.equal(ready.work_comparisons,1);
 const first=await j.request('/start?share=25&work=reviews',{assignment:null,launch:j.launch});j.session=first.session;j.held=first;
 assert.ok(first.work_check);assert.equal(first.assignment_reason.policy,'trusted assignment comparison');assert.doesNotMatch(first.brief_md,/Search the global body of work first/);
 await j.submit({work_disposition:decision(first.work_check)});
 await queueWorkCheck(w.pid,slug,null,{...t,unresolved_obligation_md:'A different exact comparison.'},stop(prior.return_id),{author_model:a.model});
 assert.equal((await j.request('/ready?work=reviews')).work_comparisons,undefined);
 const second=await j.start();assert.equal(second.type,'review');await w.finish(j);
 assert.ok((await j.request('/ready?work=reviews')).work_comparisons>=1);
 const third=await j.start();assert.ok(third.work_check);
 const scientific=await j.submit({request_review:true,work_disposition:decision(third.work_check),research_evidence:{topic_ids:t.topic_ids,scopes:[{key:'new-claim',statement_md:'A separately proposed finite observation.',domain_md:'Fixture only.',kind:'finite',artifact_sha256:[]}]}});
 assert.equal(scientific.status,'pending');assert.match(scientific.warnings.join('\n'),/ordinary intake/);assert.equal((await w.read(`/return/${scientific.return_id}`)).work_disposition,null);await w.invariant();
});
test('a broad MD5 run cannot close the track and a concrete next test is dispatched once',async()=>{
 const w=await lab.project('generic-to-specific',17),slug=config(w,'md5',true);const a=await w.actor('a','gpt-6-astra'),j=await w.actor('j','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),t=task(prior.return_id);
 const run=await job(w,t,{origin:'challenge:md5-mirror-ascii32-v1:fixture'});await w.take(a,x=>Number(x.job_id)===Number(run.id));
 const stopped=await a.submit({known_work:stop(prior.return_id)});const assigned=await w.take(j,x=>Boolean(x.work_check));assert.equal(assigned.work_check.allow_covered,false);
 const wrong=await j.submit({work_disposition:decision(assigned.work_check)});assert.match(wrong.warnings.join('\n'),/no dispatch authority/);
 const {queueWorkCheck,queueWorkNextTasks}=await import('../src/lib/work-disposition.ts');await queueWorkCheck(w.pid,slug,null,t,stop(prior.return_id),{allow_covered:false,author_model:a.model});
 const j2=await w.actor('j2','claude-fable-5-1',{trusted:true});const fresh=await w.take(j2,x=>Boolean(x.work_check));const next={...t,intent:'extend',unresolved_obligation_md:'Compare lazy three-word and all-word observers on identical streams.',changed_premise_md:'Hold kernel and seeds fixed; change observer only.'};
 await j2.submit({work_disposition:decision(fresh.work_check,{decision:'open',next_task:next})});
 await queueWorkNextTasks(w.pid,slug);await queueWorkNextTasks(w.pid,slug);const selected=await w.q("SELECT * FROM jobs WHERE problem_id=$1 AND origin_key LIKE 'work-next:%'",[w.pid]);assert.equal(selected.length,1);assert.equal(selected[0].research_task.unresolved_obligation_md,next.unresolved_obligation_md);assert.deepEqual(selected[0].research_task.predecessor_returns,[prior.return_id]);
 await w.invariant();
});
test('Twin Primes exact O2 investment decisions preserve O1/O3–O7 and the accepted main proof',async()=>{
 const w=await lab.project('operational-twin',22),slug=config(w,'twin-primes');const a=await w.actor('a','gpt-6-astra'),j=await w.actor('j','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),t=task(prior.return_id,'kk-lower-bound.o2');
 // Existing accepted main proof is a fixture; these investment helpers never change it.
 await w.q("UPDATE returns SET status='accepted',final_rung='proven',provisional=false WHERE id=$1",[prior.return_id]);
 await (await import('../src/db/index.ts')).migrate();
 const {queueWorkCheck,retireCoveredWork}=await import('../src/lib/work-disposition.ts');await queueWorkCheck(w.pid,slug,null,t,stop(prior.return_id),{author_model:a.model});
 const assigned=await w.take(j,x=>Boolean(x.work_check));await j.submit({work_disposition:decision(assigned.work_check)});
 const covered=await job(w,t),others=[];for(const topic of ['main','o1','o3','o4','o5','o6','o7'])others.push(await job(w,{...t,topic_ids:[`kk-lower-bound.${topic}`]}));await retireCoveredWork(w.pid,slug);
 assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[covered.id])).status,'expired');for(const x of others)assert.equal((await w.one('SELECT status FROM jobs WHERE id=$1',[x.id])).status,'queued');
 const main=await w.read(`/return/${prior.return_id}`);assert.equal(main.status,'accepted');assert.equal(main.final_rung,'proven');
});
test('legacy coverage packages and fileless reports remain ordinary returns; an explicit review nominates one trusted comparison',async()=>{
 const w=await lab.project('legacy-review-nomination',31),slug=config(w);const a=await w.actor('a','gpt-6-astra'),r=await w.actor('reviewer','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),t=task(prior.return_id),original=await job(w,t);
 const artifact=await a.upload('coverage.json',JSON.stringify({administrative_identity_only:true}));await w.take(a,x=>Number(x.job_id)===Number(original.id));
 const legacy=await a.submit({report_md:'Known-work comparison, no new scientific experiment. An administrative coverage package is attached.',cpu_hours:0,files:[artifact],request_review:true});assert.equal(legacy.status,'pending');assert.equal((await w.read(`/return/${legacy.return_id}`)).known_work,null);
 assert.equal((await w.one("SELECT count(*)::int AS n FROM jobs WHERE problem_id=$1 AND work_check IS NOT NULL",[w.pid])).n,0,'prose creates no nomination');
 const review=await r.submit({type:'review',return_id:legacy.return_id,verdict:'accept',rung:'heuristic',work_check:stop(prior.return_id),work_disposition:{decision:'covered',scope_sha256:workScopeHash(t),input_sha256:'a'.repeat(64),rationale_md:'No authority on an ordinary review.',reopen_when_md:'Changed input.'}});
 assert.ok(review.work_check_job_id);assert.match(review.warnings.join('\n'),/ordinary reviews cannot issue assignment authority/);
 const check=await w.one('SELECT work_check FROM jobs WHERE id=$1',[review.work_check_job_id]);assert.equal(check.work_check.source_review_id,review.review_id);assert.ok(check.work_check.sources.review_ids.includes(review.review_id));assert.ok(check.work_check.sources.predecessor_returns.includes(legacy.return_id));assert.equal(check.work_check.author_model,r.model);
 assert.deepEqual((await w.read('/work-state')).decisions,[]);assert.equal((await w.read(`/return/${legacy.return_id}`)).known_work,null);
 assert.equal((await w.read(`/review/${review.review_id}`)).research_assessment.work_check.task.unresolved_obligation_md,t.unresolved_obligation_md);
 const again=await r.submit({type:'review',return_id:legacy.return_id,verdict:'accept',rung:'heuristic',work_check:stop(prior.return_id)});assert.equal(again.work_check_job_id,review.work_check_job_id);
 assert.equal((await w.one("SELECT count(*)::int AS n FROM jobs WHERE problem_id=$1 AND work_check IS NOT NULL AND status IN ('queued','assigned')",[w.pid])).n,1);
 const second=await job(w,{...t,unresolved_obligation_md:'A distinct source-only transfer question.'});await w.take(a,x=>Number(x.job_id)===Number(second.id));
 const fileless=await a.submit({report_md:'Prior evidence covers this unchanged question; no new execution or candidate.',cpu_hours:0,request_review:true});assert.equal(fileless.status,'pending');
 const nominated=await r.submit({type:'review',return_id:fileless.return_id,verdict:'accept',rung:'heuristic',work_check:stop(prior.return_id)});assert.ok(nominated.work_check_job_id);assert.notEqual(nominated.work_check_job_id,review.work_check_job_id);
 const malformed=await r.submit({type:'review',return_id:fileless.return_id,verdict:'accept',rung:'heuristic',work_check:{predecessor_returns:[]}});assert.equal(malformed.work_check_job_id,null);assert.match(malformed.warnings.join('\n'),/still receivable/);
 const judge=await w.actor('comparison','gpt-6-astra',{trusted:true});const held=await w.take(judge,x=>Boolean(x.work_check));
 await w.q('UPDATE returns SET report_md=report_md||$2 WHERE id=$1',[prior.return_id,' A material correction after the issued source snapshot.']);
 const stale=await judge.submit({work_disposition:decision(held.work_check)});assert.match(stale.warnings.join('\n'),/stale/);assert.ok((await w.read('/work-state')).decisions.every(x=>!x.suppressed));
 await w.invariant();
});
test('concurrent nominations are scope-deduplicated and an unchanged broad task cannot be covered by a review',async()=>{
 const w=await lab.project('nomination-concurrency',32),slug=config(w,'md5',true);const a=await w.actor('a','gpt-6-astra'),r=await w.actor('reviewer','claude-fable-5-1',{trusted:true});
 const prior=await a.submit({type:'direction'}),t=task(prior.return_id);const {queueWorkCheck}=await import('../src/lib/work-disposition.ts');
 const concurrent={...t,unresolved_obligation_md:'A separate exact concurrent nomination fixture.'};const ids=await Promise.all(Array.from({length:8},()=>queueWorkCheck(w.pid,slug,null,concurrent,stop(prior.return_id),{author_model:a.model})));assert.equal(new Set(ids).size,1);
 const broad=await job(w,t,{origin:'challenge:md5-mirror-ascii32-v1:fixture'});await w.take(a,x=>Number(x.job_id)===Number(broad.id));const legacy=await a.submit({cpu_hours:0});
 const reviewed=await r.submit({type:'review',return_id:legacy.return_id,verdict:'accept',rung:'heuristic',work_check:{...stop(prior.return_id),task:t}});
 assert.notEqual(reviewed.work_check_job_id,ids[0]);assert.equal((await w.one('SELECT work_check FROM jobs WHERE id=$1',[reviewed.work_check_job_id])).work_check.allow_covered,false);await w.q("UPDATE jobs SET status='returned' WHERE id=$1",[reviewed.work_check_job_id]);
 const retry=await r.submit({type:'review',return_id:legacy.return_id,verdict:'accept',rung:'heuristic',work_check:{...stop(prior.return_id),task:t}});assert.equal((await w.one('SELECT work_check FROM jobs WHERE id=$1',[retry.work_check_job_id])).work_check.allow_covered,false);
 const narrow={...t,unresolved_obligation_md:'Compare only the declared corpus under a different observer.'};const next=await r.submit({type:'review',return_id:legacy.return_id,verdict:'accept',rung:'heuristic',work_check:{...stop(prior.return_id),task:narrow}});assert.equal((await w.one('SELECT work_check FROM jobs WHERE id=$1',[next.work_check_job_id])).work_check.allow_covered,true);
});
test('new throughput endorsements require a current fair-comparison declaration while unrelated scopes and candidate history are untouched',async()=>{
 const w=await lab.project('comparison-endorsement',33);config(w);const a=await w.actor('a','gpt-6-astra'),r=await w.actor('reviewer','claude-fable-5-1',{trusted:true});
 const scope={key:'rate',statement_md:'A fixture claims a rate advantage.',domain_md:'Specified full-MD5 fixture.',assumptions_md:'Matched observations.',kind:'throughput',artifact_sha256:[],transfer_conditions_md:'No universal attack claim.'};const finite={...scope,key:'finite',kind:'finite',statement_md:'A separate finite fixture observation.'};
 const authored=await a.submit({type:'direction',research_evidence:{topic_ids:['all-zeros.methods'],scopes:[scope,finite]}});const read=await w.read(`/return/${authored.return_id}`);assert.equal(read.report_sha256,reportHash(read.report_md));
 const refs=[scope,finite].map(s=>({scope_key:s.key,scope_sha256:scopeHash(s)}));
 const missing=await r.submit({type:'review',return_id:authored.return_id,verdict:'accept',rung:'measured',research_assessment:{supported_scopes:refs}});assert.match(missing.warnings.join('\n'),/current complete comparison checks/);assert.deepEqual((await w.read(`/review/${missing.review_id}`)).research_assessment.supported_scopes,[refs[1]]);
 const c={report_sha256:read.report_sha256,scope_key:'rate',scope_sha256:scopeHash(scope),kind:'hit_rate',method:{unit:'final_iterate',observations:20000,successes:1276,work_budget_md:'Only 160000 final hashes charged; 60 MD5 steps per solve iteration omitted.'},baseline:{unit:'digest_output',observations:160000,successes:9800,work_budget_md:'All 160000 outputs counted.'},selection_stopping_md:'Only final iterates sampled versus every baseline output.',baseline_equivalence_md:'The two selected events differ.',uncertainty_md:'The current comparison lacks adequate normalized uncertainty.',budget_complete:false,baseline_equivalent:false,uncertainty_adequate:false};
 const bad=await r.submit({type:'review',return_id:authored.return_id,verdict:'accept',rung:'measured',research_assessment:{supported_scopes:refs,comparison_checks:[c]}});assert.match(bad.warnings.join('\n'),/different counted observation units/);assert.deepEqual((await w.read(`/review/${bad.review_id}`)).research_assessment.supported_scopes,[refs[1]]);
 const valid={...c,method:{...c.method,unit:'digest_output',work_budget_md:'All preprocessing, 60-step solves, full hashes and verification counted.'},baseline_equivalence_md:'Same output event and controls, unequal sample counts normalized.',selection_stopping_md:'Fixed counts with every declared output counted and dependence disclosed.',uncertainty_md:'Reviewer-inspected uncertainty at the stated scope.',budget_complete:true,baseline_equivalent:true,uncertainty_adequate:true};
 const good=await r.submit({type:'review',return_id:authored.return_id,verdict:'accept',rung:'measured',research_assessment:{supported_scopes:refs,comparison_checks:[valid]}});assert.deepEqual((await w.read(`/review/${good.review_id}`)).research_assessment.supported_scopes,refs);
 const conflict=await r.submit({type:'review',return_id:authored.return_id,verdict:'accept',rung:'measured',research_assessment:{supported_scopes:refs,comparison_checks:[valid,c]}});assert.deepEqual((await w.read(`/review/${conflict.review_id}`)).research_assessment.supported_scopes,[refs[1]],'a valid first check cannot mask contradictory checks for the same scope');
 const stale=await r.submit({type:'review',return_id:authored.return_id,verdict:'accept',rung:'measured',research_assessment:{supported_scopes:refs,comparison_checks:[{...valid,report_sha256:'0'.repeat(64)}]}});assert.match(stale.warnings.join('\n'),/stale report hash/);assert.deepEqual((await w.read(`/review/${stale.review_id}`)).research_assessment.supported_scopes,[refs[1]]);
});
test('input-verified accepted reports can request bounded trusted research triage without changing candidate status or decisions',async()=>{
 const w=await lab.project('verified-report-triage',34);config(w);const a=await w.actor('a','gpt-6-astra');const ret=await a.submit({type:'direction'});
 await w.q("UPDATE returns SET status='accepted',final_rung='verified',provisional=false WHERE id=$1",[ret.return_id]);await w.q("INSERT INTO return_decisions(return_id,status,final_rung,provisional,by,note) VALUES($1,'accepted','verified',false,'verifier','Fixture verifies an input only.')",[ret.return_id]);
 const before=await w.one('SELECT count(*)::int AS n FROM return_decisions WHERE return_id=$1',[ret.return_id]);const beforeReviews=await w.one("SELECT count(*)::int AS n FROM jobs WHERE parent_return_id=$1 AND type='review'",[ret.return_id]);
 await a.request(`/return/${ret.return_id}/request-review`,{method:'POST',body:{note:'Inspect the consequential report comparison.'},status:409});
 const body={scope:'research_report',note:'Inspect the mismatched histogram units and uncharged solve work.'};const first=await a.request(`/return/${ret.return_id}/request-review`,{method:'POST',body});const second=await a.request(`/return/${ret.return_id}/request-review`,{method:'POST',body});
 assert.ok(first.work_check_job_id);assert.equal(second.work_check_job_id,first.work_check_job_id);assert.equal(first.status,'accepted');assert.equal(first.final_rung,'verified');assert.equal(first.reviews_requested,0);
 assert.equal((await w.one('SELECT work_check FROM jobs WHERE id=$1',[first.work_check_job_id])).work_check.allow_covered,false);assert.deepEqual(await w.one('SELECT count(*)::int AS n FROM return_decisions WHERE return_id=$1',[ret.return_id]),before);
 const after=await w.read(`/return/${ret.return_id}`);assert.equal(after.status,'accepted');assert.equal(after.research_authority.witness_status,'verified input');assert.equal(after.research_authority.research_status,'research report unreviewed');assert.deepEqual(await w.one("SELECT count(*)::int AS n FROM jobs WHERE parent_return_id=$1 AND type='review'",[ret.return_id]),beforeReviews);
 const paper=await a.submit({type:'direction'});await w.q("UPDATE returns SET status='accepted',final_rung='proven' WHERE id=$1",[paper.return_id]);await a.request(`/return/${paper.return_id}/request-review`,{method:'POST',body,status:409});
});
